### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by TheBestYTech** [A-c0rN/EASGen#2]
When I try to save or play an EAS file, even if running python from an elevated CMD, I get this error:

"PermissionError: [Errno 13] Permission denied: 'C:\\Users\\(Redacted For Privacy)\\AppData\\Local\\Temp\\tmppxj652pv.wav'"

**Comment by A-c0rN** [comment]
This isn't an issue with EASGen, this is an issue with pydub running in an elevated environment. If you want this to work properly, try to run not in an elevated command prompt.
